### ISSUE TITLE
Profiles is supplied as an [] and is returned (in raw) as an array with a single string

### ISSUE THREAD

**Issue by itonics-tbeauvais** [victorherraiz/cloud-config-client#10]
This should at least be consistent. It really doesn't matter which, so long as we get out what we put in.

For instance, when initialized by following upon fetching the configuration:
```
                    const profiles = await environment.get("PROFILES", "dev,local").split(",");

                    console.debug("initializing cloud-config-client with profiles", profiles);

                    return require("cloud-config-client").load({
                        endpoint: url,
                        application: "hello-service",
                        profiles: profiles
                    }).then((client: any) => {
                        this.client = client;

                        return this;
                    });

```

Note that we have to split the incoming to assign an array from an environment variable. This makes sense!

When we print out the configuration "raw" we can see that it's not a concatenated string:

```
{
    profiles: {
    name: "hello-service",
    profiles: [
        "dev,local"
    ],
    ...
}
```
I'd recommend something simple like adding this array to the object created by the cloud-config-client to remain consistent.

**Comment by victorherraiz** [comment]
Thank you for your feedback. 

Raw property contains the server response with no alterations. I do not know if this attribute has changed between Spring Cloud Config Server versions. Could you please tell the version that you are using? (I would like to compare the response agains the original I used to develop the client). We should not try to normalice the info in that response, only process the properties and make them accesible as simple as possible. 

One useful feature, as I saw in your example,  could be: accept strings (comma separated) and arrays in the profile parameter. Any thoughts?
