### ISSUE TITLE
Use cloud config client behind company proxy

### ISSUE THREAD

**Issue by guillaume-lecomte** [victorherraiz/cloud-config-client#11]
Hello,
First thanks for this project :)
I would like to use it behind a company proxy, how can I configure the options to achieve this ?

Thanks

**Comment by victorherraiz** [comment]
Hi @Triann, 
could you please explain your use case with more detail?  What kind of proxy?

At the moment, we did not have option for setting a proxy for the client's request (apart from globalAgent). In my company and at others cloud config servers are in the  same network as the client (even in the same PaaS project). 

I could do a small development and add an option for agent to provide the support for proxies using something like [https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent)

**Comment by guillaume-lecomte** [comment]
Hi @victorherraiz 
Thanks for your quick answer ! 

I would like to add a proxy url to pass the request, like "http://myproxy:8080".

Regards

**Comment by victorherraiz** [comment]
Thanks, I will add a parameter for the agent and some examples next weekend.

**Comment by victorherraiz** [comment]
I added the parameter and released version 1.2.0, update your `package.json` or your `yarn.json`.

You can use the agent parameter to make requests throw a proxy using, for example, https-proxy-agent or http-proxy-agent.

example (adapted from https-proxy-agent website):

```js
const https = require('https')
const HttpsProxyAgent = require('https-proxy-agent')
const client = require('cloud-config-client')

const proxy = process.env.http_proxy || 'http://168.63.76.32:3128'
console.log('using proxy server %j', proxy)
const agent = new HttpsProxyAgent(proxy)

const options = {
  application: 'demo',
  profiles: ['test', 'timeout'],
  agent
}
client.load(options).then((cfg) => {
  console.log(cfg.get('test.users', 'multi.uid'))
  console.log(cfg.toString(2))
}).catch((error) => console.error(error))

```

does this solution work for you?

**Comment by guillaume-lecomte** [comment]
Hi Victor,
Thanks for your message and update ! I'll try this :)
Regards

**Comment by victorherraiz** [comment]
@Triann I close this issue, If you have any problems reopen it or add other ticked. Thank you so much for reporting your problem
