### ISSUE TITLE
Resolve placeholders, as in Java

### ISSUE THREAD

**Issue by jhbarrantes** [victorherraiz/cloud-config-client#13]
Hi Victor! 

it will be great if the cloud config client could resolve placeholders for environment variables, as the client in Java. I mean, to be able to put the following in a .yml, and for the client to be able to resolve these placeholder: 

```
an:
  example:
    username: ${MY_USERNAME}
    password: ${MY_PASSWORD}
```

Been these `MY_USERNAME ` and `MY_PASSWORD` two environment variables, resolved from nodejs environment (process.env).

That way, we can map environment variables to .yml properties, whithout having to do this manually at the code, playing with process.env.X

Thanks!

**Comment by victorherraiz** [comment]
This an interesting feature, I will take a look this weekend. Maybe simple post-processor...

**Comment by RecuencoJones** [comment]
Maybe https://www.npmjs.com/package/lodash.template could be used?

https://github.com/victorherraiz/cloud-config-client/blob/5e8666b1d57d00abf4d6ff6a966919fd7f591247/index.js#L124

```
const templateFn = _.template(response)
const body = JSON.parse(templateFn(process.env))
```

**Comment by victorherraiz** [comment]
@RecuencoJones, the format must be  `${NAME}`, I check the lodash.template and it is configurable. The problem this approach is that it could make the JSON string invalid if it is not properly escaped. 

We could use a simple JSON reviver to process every string in the result  or do it lazy on get. 


```js
      const env = { WORLD: 'mundo' }
      const replacer = (str) => str.replace(
        /\$\{(.+?)\}/g,
        (match, group) => env[group] || match)

      assert.strictEqual(
        // eslint-disable-next-line
        replacer('hello ${WORLD}!, bye ${WORLD}!'),
        'hello mundo!, bye mundo!')
```

**Comment by victorherraiz** [comment]
Unfortunately we cannot add this behaviour by default, someone could be already doing something and we could break their implementations.

Two options: option parameter or new version

**Comment by jhbarrantes** [comment]
That's a good one Victor, maybe it is time to release version 2 of the service!

Another consideration, from my example:

```
an:
  example:
    username: ${MY_USERNAME}
    password: ${MY_PASSWORD}
```

if _MY_USERNAME_ and _MY_PASSWORD_ are not defined as environment variables, the load of the yml will set ups as null values (or make the app failing to start in case of a bootstrap yml). A way of resolving this is just to provide a default value, in case the environment variable is not declared:

```
an:
  example:
    username: ${MY_USERNAME:javier}
    password: ${MY_PASSWORD:superpassword}
```

Where _javier_  and _superpassword_ are the default values to be mapped to an.example.username and an.example.password, in case _MY_USERNAME_ and _MY_PASSWORD_ are not defined in the environment.

Think we should take this in consideration as well. 

Regards.

**Comment by ttola** [comment]
+1 for a new version and support for optional defaults. 

Using @victorherraiz  and @jhbarrantes default interpolation example;

``` javascript
const replacer = str =>
    str.replace(/\$\{(.+?)\}/g, (match, group) => {
        let [groupKey, groupDefaultValue] = group.split(':');
        return env[groupKey] || groupDefaultValue || match;
    });
```

**Comment by victorherraiz** [comment]
Published in version 1.4.2, see readme for more details (Context references)

**Comment by jhbarrantes** [comment]
Amazing Victor! If I'm not wrong, only change will be to pass this new parameter to the Client.load function, isn't it? So, as long as we call the function with `context: process.env`, it should resolve the placeholders found in the configuration, referencing an environment variable declared at process.env, right?

**Comment by victorherraiz** [comment]
That is. Until version 2 I cannot break compatibility, therefore you need to do a small change in your code. This will be the default behaviour in version 2.

**Comment by michaelliao** [comment]
@victorherraiz Please consider support nested placeholder like ${KEY:${DEFAULT:12345}} which is supported by Spring cloud config Java client.

Regards.
