### ISSUE TITLE
Reload/Refresh Configuration without restarting the service

### ISSUE THREAD

**Issue by sarahwalker123** [victorherraiz/cloud-config-client#15]
-  Spring Boot services have an **/refresh** endpoint provided by the Actuator which can help in reloading the configuration.

- Is there a similar way to reload/refresh the configuration without restarting the service.

**Comment by fabb** [comment]
I guess such an endpoint would need to be implemented manually in the server code since this package does not make any assumptions on which server (express etc.) is used.

**Comment by victorherraiz** [comment]
Evert time you call load you get a new copy of the configuration, the problem is to update the actual configuration in your services. Refresh is always a problem, sometimes is much better (and simple) solution just restart, especially at PaaS (e.g. Kubernetes)
