### ISSUE TITLE
add *.d.ts file

### ISSUE THREAD

**Issue by daniyel** [victorherraiz/cloud-config-client#16]
Hi.

It would be nice to add a `d.ts` file to the package.

Best regards.

**Comment by daniyel** [comment]
Hi.

I did pull request here https://github.com/victorherraiz/cloud-config-client/pull/17/commits/17c64c742de605b519d2f1658f0014a3bbd6adfa, you can check it out and merge, if you want.

Best regards.

**Comment by victorherraiz** [comment]
done, sorry for the terrible delay
