### ISSUE TITLE
Authentication fails for password using cipher

### ISSUE THREAD

**Issue by lijod** [victorherraiz/cloud-config-client#18]
When I pass username and password in plain text, it works fine, but when I use password containing cipher, it fails to authenticate. Example,
```
auth: {
            user: "username",
            pass: "{cipher}4945f492dc8fa3748863bf530665456cd67f46f68fe479174b21c450602132ef"
        }
```
Note: I use cipher string in spring boot application using _spring.cloud.config.password_ and it works, which means Spring Config Server recognizes cipher based password.

**Comment by victorherraiz** [comment]
I did not that this feature even exists, I will do a simply test, it could be a problem in the encoding.

**Comment by victorherraiz** [comment]
I was not able to reproduce the issue, sorry. After reading the docs I did not see the option to do that. Please, open the issue if there is still a need for that.
