### ISSUE TITLE
Retry

### ISSUE THREAD

**Issue by fabb** [victorherraiz/cloud-config-client#21]
The Spring Java Implementation Client supports request retrial in case the config server wasn't reachable on server start. It would be nice if this library would support that as well.

http://cloud.spring.io/spring-cloud-config/2.0.x/single/spring-cloud-config.html#config-client-retry

> If you expect that the config server may occasionally be unavailable when your app starts, you can ask it to keep trying after a failure. First you need to set spring.cloud.config.failFast=true, and then you need to add spring-retry and spring-boot-starter-aop to your classpath. The default behaviour is to retry 6 times with an initial backoff interval of 1000ms and an exponential multiplier of 1.1 for subsequent backoffs. You can configure these properties (and others) using spring.cloud.config.retry.* configuration properties.

**Comment by victorherraiz** [comment]
load method could be wrap into a simple code to do that functionality. You could use node-promise-retry. Therefore this should be out of the scope
