### ISSUE TITLE
Not able to get refreshed value

### ISSUE THREAD

**Issue by iamsandeepgupta** [victorherraiz/cloud-config-client#23]
I have done all the config for the spring cloud server and also implemented the client in my node.js app but when I refresh any value in my DB which is connected to my spring cloud server the values on my node app didn't get refreshed.

[config.txt](https://github.com/victorherraiz/cloud-config-client/files/4069849/config.txt)

**Comment by RecuencoJones** [comment]
Hi @iamsandeepgupta, this might be related to https://github.com/victorherraiz/cloud-config-client/issues/15

From what I recall, this library does not have an integration for hot reload of configuration once it is updated in the source, you would need to restart the service to get the changes.

**Comment by victorherraiz** [comment]
Reloading is a big issue, even many Spring app. discard that option. It require connection to a bus to get the event and your code has to support  hot reloading. That is quite "out of the scope" for this project.

You could implement something to "load" your configuration at fixed intervals, but the problem of hot reloading still there: open new connections, close the old ones...
