### ISSUE TITLE
Add support to put the config into environment variables?

### ISSUE THREAD

**Issue by LionC** [victorherraiz/cloud-config-client#3]
As Docker is so popular now, configuring applications with environment variables has become kind of a standard, causing more and more applications and libraries to rely on / offer configuration with environment variables.

Our company is heavy microservice oriented and uses env variable config for Node applications. I found your module when searching for a way to integrate them into our Spring Cloud Config. It would be awesome if the module would have an option to automatically put the loaded configs into `process.env` (following the convention of replacing `.` with `_` and capitalizing everything).

It would be no problem to write an own module to do that, I just thought that I am likely not the only one with that goal. I'd be glad to create a pull request implementing that feature (and documenting it of course) if you are open for that.

**Comment by victorherraiz** [comment]
Hi, I think that process is out of scope of this utility. It only queries, as simple as possible, config server values.

If you what to use it as a source of configuration in your application with other possible sources (e.g. Env. Variables, external yml files) you should use something like a proxy context.

Very naive and dummy example:

``` js
function get(key) {
    const keyenv = formatAsEnvKey(key);
    if (process.env[keyenv]) {
         return process.env[keyenv];
    }
    // Add more sources here
    // Config from cloud-config-client
    return config.get(key);
}
```

**Comment by LionC** [comment]
I think you misunderstood my proposal. I do not want to **load** environment variable configs with your module (that'd certainly be out of scope), but rather make your module **put** the config it loaded into the `process.env` object. Example:

```
var loadConfig = require('cloud-config-client');

loadConfig({
    name: 'exampleApplication',
    loadToEnv: true //Not the final name obv
}).then(function(config) {
    //Here, all loaded config keys are also available on the process.env object,
    //so that it looks like env variable config to libraries that depend on env variables
});
```

As Node makes it possible to just set properties on `process.env`without any effect to the outside world, this change would be very easy and I would be happy to implement it :-)

**Comment by victorherraiz** [comment]
Sorry for the late reply, I just publish a new version. 

The config object returned by load has a forEach method. With that method you could easily implement your requirement in your project.

I decided to keep this project as simple as possible.
