### ISSUE TITLE
Hello, unable to install plugin using "npm i cloud-config-client"

### ISSUE THREAD

**Issue by munibcloudsufi** [victorherraiz/cloud-config-client#40]
Hi Team,
Thank you for plugin, but somehow we are not able to install using. "https://www.npmjs.com/package/cloud-config-client". please help!

**Comment by RecuencoJones** [comment]
Hi @munibcloudsufi 
Could you please share some logs with the actual error you're facing?
Thanks

**Comment by munibcloudsufi** [comment]
Thank you for quick connect. screenshot attached. 
![E404](https://user-images.githubusercontent.com/61404912/119985646-8cc17400-bfe0-11eb-8207-a5e92f9fe753.png)
It's E404 while try  to install plugin using "npm i cloud-config-client"

**Comment by munibcloudsufi** [comment]
while click on link https://npm.pkg.github.com/fffEnterprises/cloud-config-client/-/cloud-config-client-1.5.2.tgz, it's not found. seems like npm registry has some issue.

**Comment by RecuencoJones** [comment]
Hi again,
Yes, this definitely seems an issue with that private registry not being able to resolve modules from the public npm registry
I'm not sure how exactly github npm registry works, but looking at this:

> When you route all package requests through GitHub Packages, you can use both scoped and unscoped packages from npmjs.com.

the public mirror should be managed by GitHub itself.

**Comment by munibcloudsufi** [comment]
Hi, Just reverified everything and found issue is not actually related to npm package itself. it's come due to github token policy change. if you are using .npmrc file in your private github repository and token change i.e. 

//npm.pkg.github.com/:_authToken=xxxxxxxxxxx
registry=https://npm.pkg.github.com/{your_private_repository_name}

Solution: make sure to re-generate token and replace in .npmrc file or enviorment.

step to generate github token: login >> profile >> account >> developer setting >> generate personal token.

closing issue. @RecuencoJones  Thank you very much for help!
