### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by victorherraiz** [victorherraiz/cloud-config-client#5]
Support HTTPS endpoints. Add insecure option.

**Comment by blueleader07** [comment]
+1

**Comment by puttareddy** [comment]
+1

**Comment by victorherraiz** [comment]
I have to merge a pull request this weekend and I will work on this issue next week. I'm going to include an option for `insecure` connections as many people use self-sign certificates

**Comment by puttareddy** [comment]
I have given pull request#8 with this feature. Please review and approve.

**Comment by victorherraiz** [comment]
Done. 
Sorry @puttareddy, I already did the changes by myself some days ago.
